Fix/Send proposal upload files
ZenBit-Tech/HiveIn_fe pull request #61
Opened 2022-10-14 04:34 UTC by jphinning

2022-10-14 10:18 UTC, DavidSurkov requested changes

2022-10-14 10:18 UTC, DavidSurkov commented on src/components/UI/ModalWindows/SubmitProposalModal/SubmitProposalModal.tsx
> +  };
what if you move all this logic into the custom hook? you will isolate all the logic

2022-10-16 10:16 UTC, DavidSurkov approved these changes

2022-10-17 17:20 UTC, lyudad approved these changes

2022-10-17 18:23 UTC, merged